### ISSUE TITLE
Run tget in background

### ISSUE THREAD

**Issue by ErikTrapman** [jeffjose/tget#11]
Is it possible to run `tget` as background process? I'm struggling to get this to work, following instructions such as https://stackoverflow.com/questions/954302/how-to-make-a-programme-continue-to-run-after-log-out-from-ssh
Is there a known limitation that holds tget from running as a background process?

**Comment by jeffjose** [comment]
Typically programs dont run as orphans/daemons unless you make it too. The details of it are too long to describe here, but the easy solution would be to have a `parent` process control `tget`. `supervisord` one such tool.

That said, the best solution for you would be something as follows
1. ssh into a remote machine
2. start `screen` or `tmux`
3. start `tget` 
4. logout.

At a later time, when you `ssh` back in, you attach to the previous `screen` or `tmux` session.

**Comment by ErikTrapman** [comment]
I've got tmux running now, seems to be working fine. Thanks for explaining, even though it is not strictly related to `tget`. Cheers!
