### ISSUE TITLE
Where is the download location

### ISSUE THREAD

**Issue by Deep-sea-boy** [jeffjose/tget#13]
when i use tget "XXXXXX" , Where is the download location?

**Comment by jeffjose** [comment]
The download location is wherever you run `tget` from.
```
$ pwd
/home/deepseaboy/Downloads/ubuntu

# Download to the current dir.
$ tget 'magnet:xxxxxxxxx'

```

**Comment by Deep-sea-boy** [comment]
`/usr/local/bin/tget "magnet:?xt=urn:btih:faffd59586841154f6929357c628e874bc0c373b"`

**Comment by Deep-sea-boy** [comment]
`/usr/local/bin/tget "magnet:?xt=urn:btih:faffd59586841154f6929357c628e874bc0c373b"`
nothing change , It's like stuck , no text or process is displayed , what should i do ？ Maybe my network doesn't support over the wall to download this link？

**Comment by jeffjose** [comment]
Do you face the same issue with other magnet links? What happens if you try to download the latest ubuntu?
