### ISSUE TITLE
/usr/local/bin/tget 'xxx' Nothing happened...

### ISSUE THREAD

**Issue by sunjunyi** [jeffjose/tget#15]
Hello, I installed tget on my Mac,  there is no change after I input the command :
(**tget magnet:? XT= urn:btih : 0403fb4728bd788fbb67e87d6feb241ef38c75a**  or 
 **/usr/local/bin/tget magnet:? XT= urn:btih : 0403fb4728bd788fbcb67e87d6feb241ef38c75a**),
 What should I do with it?

**Comment by jeffjose** [comment]
Are you quoting the magnet string? 

Dont do 
```
$ tget magnet:?xt=urn:btih:L77Q4HEKYQKIMAYQXTA4W5VMFDUWB356&dn=ubuntu-20.10-desktop-amd64.iso&xl=2942003200&tr=https%3A%2F%2Ftorrent.ubuntu.com%2Fannounce
```

But instead put quotes `"` or `'` around the magnet string
```
$ tget 'magnet:?xt=urn:btih:L77Q4HEKYQKIMAYQXTA4W5VMFDUWB356&dn=ubuntu-20.10-desktop-amd64.iso&xl=2942003200&tr=https%3A%2F%2Ftorrent.ubuntu.com%2Fannounce'
```
