### ISSUE TITLE
Just the torrent file

### ISSUE THREAD

**Issue by jikkujose** [jeffjose/tget#3]
Just stumbled on this, great work there! Was thinking, whether this can be used to download just the torrent file rather than downloading what the torrent file holds?

**Comment by jeffjose** [comment]
Maybe this is obvious, but if you have a link to torrent a simple 'wget'
will work. If you have a magnet link, it's a different thing all together.

**Comment by jikkujose** [comment]
Sure, but how do I get the link for the torrent file? I was assuming the file was getting downloaded from a DHT in a different way than ordinary http connection.
