### ISSUE TITLE
run tget but it output nothing

### ISSUE THREAD

**Issue by yo123abxd** [jeffjose/tget#7]
I install tget success and can run "$ tget "
it output "Usage: tget magnet-link-or-torrent"

but when i type "$ tget 'magnet:xt=urn:btih:0403fb4728bd788fbcb67e87d6feb241ef38c75a'"
it seem stuck and output nothing

**Comment by yo123abxd** [comment]
the system is centos7

**Comment by jeffjose** [comment]
I just updated a new version. Can you install the new version and try it?

**Comment by jeffjose** [comment]
Looks like your magnet link is incorrect. I'd recommend double checking whether you have a valid-magnet link as the input to `tget`
